
package seat.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SeatServer", targetNamespace = "http://seat/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SeatServer {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns seat.CarSeat
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createCarSeat", targetNamespace = "http://seat/", className = "seat.CreateCarSeat")
    @ResponseWrapper(localName = "createCarSeatResponse", targetNamespace = "http://seat/", className = "seat.CreateCarSeatResponse")
    @Action(input = "http://seat/SeatServer/createCarSeatRequest", output = "http://seat/SeatServer/createCarSeatResponse")
    public CarSeat createCarSeat(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns seat.CarSeat
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCarSeatById", targetNamespace = "http://seat/", className = "seat.GetCarSeatById")
    @ResponseWrapper(localName = "getCarSeatByIdResponse", targetNamespace = "http://seat/", className = "seat.GetCarSeatByIdResponse")
    @Action(input = "http://seat/SeatServer/getCarSeatByIdRequest", output = "http://seat/SeatServer/getCarSeatByIdResponse")
    public CarSeat getCarSeatById(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCountCarSeat", targetNamespace = "http://seat/", className = "seat.GetCountCarSeat")
    @ResponseWrapper(localName = "getCountCarSeatResponse", targetNamespace = "http://seat/", className = "seat.GetCountCarSeatResponse")
    @Action(input = "http://seat/SeatServer/getCountCarSeatRequest", output = "http://seat/SeatServer/getCountCarSeatResponse")
    public Integer getCountCarSeat();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns seat.BabyCarriage
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createBabyCarriage", targetNamespace = "http://seat/", className = "seat.CreateBabyCarriage")
    @ResponseWrapper(localName = "createBabyCarriageResponse", targetNamespace = "http://seat/", className = "seat.CreateBabyCarriageResponse")
    @Action(input = "http://seat/SeatServer/createBabyCarriageRequest", output = "http://seat/SeatServer/createBabyCarriageResponse")
    public BabyCarriage createBabyCarriage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns seat.BabyCarriage
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBabyCarriageById", targetNamespace = "http://seat/", className = "seat.GetBabyCarriageById")
    @ResponseWrapper(localName = "getBabyCarriageByIdResponse", targetNamespace = "http://seat/", className = "seat.GetBabyCarriageByIdResponse")
    @Action(input = "http://seat/SeatServer/getBabyCarriageByIdRequest", output = "http://seat/SeatServer/getBabyCarriageByIdResponse")
    public BabyCarriage getBabyCarriageById(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCountBabyCarriage", targetNamespace = "http://seat/", className = "seat.GetCountBabyCarriage")
    @ResponseWrapper(localName = "getCountBabyCarriageResponse", targetNamespace = "http://seat/", className = "seat.GetCountBabyCarriageResponse")
    @Action(input = "http://seat/SeatServer/getCountBabyCarriageRequest", output = "http://seat/SeatServer/getCountBabyCarriageResponse")
    public Integer getCountBabyCarriage();

}
