
package seat.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "seat", targetNamespace = "http://seat/", wsdlLocation = "http://localhost:8080/SeatService?wsdl")
public class Seat
    extends Service
{

    private final static URL SEAT_WSDL_LOCATION;
    private final static WebServiceException SEAT_EXCEPTION;
    private final static QName SEAT_QNAME = new QName("http://seat/", "seat");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/SeatService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SEAT_WSDL_LOCATION = url;
        SEAT_EXCEPTION = e;
    }

    public Seat() {
        super(__getWsdlLocation(), SEAT_QNAME);
    }

    public Seat(WebServiceFeature... features) {
        super(__getWsdlLocation(), SEAT_QNAME, features);
    }

    public Seat(URL wsdlLocation) {
        super(wsdlLocation, SEAT_QNAME);
    }

    public Seat(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SEAT_QNAME, features);
    }

    public Seat(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Seat(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SeatServerAsync
     */
    @WebEndpoint(name = "SeatServerAsync")
    public SeatServerAsync getSeatServerAsync() {
        return super.getPort(new QName("http://seat/", "SeatServerAsync"), SeatServerAsync.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SeatServerAsync
     */
    @WebEndpoint(name = "SeatServerAsync")
    public SeatServerAsync getSeatServerAsync(WebServiceFeature... features) {
        return super.getPort(new QName("http://seat/", "SeatServerAsync"), SeatServerAsync.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SEAT_EXCEPTION!= null) {
            throw SEAT_EXCEPTION;
        }
        return SEAT_WSDL_LOCATION;
    }

}
